language: ruby
rvm:
  - 2.1
install:
  - bundle install
  - gem install nokogiri
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --assume-extension=".html" --check-html
branches:
  only:
  - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
