language: ruby
rvm: 2.2.0

install: gem install jekyll html-proofer

script: 
- jekyll build 
- htmlproof ./_site

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
